WebApplication11/Models/tümsiniflarim/Marka.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication11.Models.tümsiniflarim
{
    public class Marka
    {
        [Key]
        public int ID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(20, ErrorMessage = "Marka Adı bilgisi 20 karakterden uzun olamaz !")]
        [Required(ErrorMessage = "Bu alan boş bırakılamaz !!")]
        [Display(Name = "Marka Adı")]
        public string Ad { get; set; }


        public ICollection<Urun> Uruns { get; set; }
    }
}

WebApplication11/Controllers/MarkaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication11.Models.tümsiniflarim;

namespace WebApplication11.Controllers
{
    [Authorize]
    public class MarkaController : Controller
    {
        Context c = new Context();
        // GET: Kategori
        public ActionResult Index()
        {
            var kategori = c.Markas.ToList();
            return View(kategori);
        }
        [HttpGet]
        public ActionResult MarkaEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MarkaEkle(Marka k)
        {
            if (!ModelState.IsValid)
            {
                return View("MarkaEkle");
            }
            c.Markas.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MarkaSil(int id)
        {
            var kategori = c.Markas.Find(id);
            c.Markas.Remove(kategori);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MarkaGetir(int id)
        {
            var secilen = c.Markas.Find(id);
            return View("MarkaGetir", secilen);
        }

        public ActionResult MarkaGuncelle(Marka k)
        {
            var ktg = c.Markas.Find(k.ID);
            ktg.Ad = k.Ad;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication11/Views/Marka/Index.cshtml
@using WebApplication11.Models.tümsiniflarim
@model List<Marka>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px; margin-left:20px;width:1080px;width:100%">
    <tr style="background-color:#000000; color:white;">

        <th>MARKA ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Ad</td>
            <td>@Html.ActionLink("Sil", "MarkaSil", new { id = x.ID }, new { @class = "btn btn-danger", @style = "Background-color:red", onclick = "return confirm('Markayı Gerçekten Silmek İstiyor Musunuz?')" }) </td>
            <td>@Html.ActionLink("Güncelle", "MarkaGetir", new { id = x.ID }, new { @class = "btn btn-default", @style = "background-color:orangered; color:white;" })</td>

        </tr>
    }
</table>
@Html.ActionLink("Marka Ekle", "MarkaEkle", new { }, new { @class = "btn btn-default", @style = "background-color:blue; color:white; margin-top:15px; margin-left:20px;" })

WebApplication11/Views/Marka/MarkaEkle.cshtml
@model WebApplication11.Models.tümsiniflarim.Marka
@{
    ViewBag.Title = "MarkaEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align:center; color:red; margin-top:20px;"> Marka Ekleme Sayfası</h1>
@using (Html.BeginForm("MarkaEkle", "Marka", FormMethod.Post, new { @style = "margin-top:30px;" }))
{
    <div>
        @Html.LabelFor(x => x.Ad, new { @style = "margin-left:30px; font-weight:bold; " })
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", @style = "margin-left:30px; width:1000px" })
        @Html.ValidationMessageFor(x => x.Ad, "", new { @style = "color:red; margin-left:30px;" })
    </div>
    <button class="btn btn-default" style="background-color:blue; color:white;margin-left:30px;">Kaydet</button>
    @Html.ActionLink("İptal", "Index", new { }, new { @class = "btn btn-primary", @style = "background-color:red; color:white" })
}

WebApplication11/Views/Marka/MarkaGetir.cshtml
@model WebApplication11.Models.tümsiniflarim.Marka
@{
    ViewBag.Title = "MarkaGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("MarkaGuncelle", "Marka", FormMethod.Post))
{

    @Html.LabelFor(x => x.ID, new { @style = "margin-left:30px; font-weight:bold;margin-top:30px; " })
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control", @readonly = "readonly", @style = "margin-left:30px; width:1080px" })
    <br />
    @Html.LabelFor(x => x.Ad, new { @style = "margin-left:30px; font-weight:bold; " })
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", @style = "margin-left:30px; width:1080px" })    
    <br />

    <button class="btn btn-default" style="background-color:green;margin-left:30px; color:white;">Güncelle</button>
    @Html.ActionLink("İptal","Index",new { },new { @class="btn btn-primary" ,@style="background-color:red; color:white"})
}