WebApplication11/Controllers/AdminController.cs
using WebApplication11.Models.tümsiniflarim;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stok_Takip_Web.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        Context c = new Context();
        // GET: Personeller
        public ActionResult Index()
        {
            var pers = c.Admins.ToList();
            return View(pers);
        }
        [HttpGet]
        public ActionResult AdminEkle()
        {
            if (!ModelState.IsValid)
            {
                return View("AdminEkle");
            }
            
            return View();
        }
        [HttpPost]
        public ActionResult AdminEkle(Admin p)
        {
            c.Admins.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AdminSil(int id)
        {
            var per = c.Admins.Find(id);
            c.Admins.Remove(per);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AdminCagir(int id)
        {
           
            var per = c.Admins.Find(id);
            return View("AdminCagir", per);
        }

        public ActionResult AdminGuncelle(Admin p)
        {
            var per = c.Admins.Find(p.ID);
            per.Ad = p.Ad;
            per.Soyad = p.Soyad;
            per.TC = p.TC;
           
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        

    }
}

WebApplication11/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication11.Models.tümsiniflarim;
namespace WebApplication11.Controllers
{
    public class AnasayfaController : Controller
    {
        Context c = new Context();
        // GET: Anasayfa
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Hakkimizda()
        {
            return View();
        }
        public ActionResult Iletisim()
        {
            return View();
        }
        public ActionResult Opel()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 15).ToList();
           
            return View(markalar);
        }
        public ActionResult Araclar()
        {
            var kategori = c.Markas.ToList();
            return View(kategori);
        }
        public ActionResult Renault()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 12).ToList();

            return View(markalar);
        }
        public ActionResult Citroen()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 9).ToList();

            return View(markalar);
        }
        public ActionResult Toyota()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 14).ToList();

            return View(markalar);
        }
        public ActionResult Aston()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 5).ToList();

            return View(markalar);
        }
        public ActionResult Fiat()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 10).ToList();

            return View(markalar);
        }
        public ActionResult Wolsvagen()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 13).ToList();

            return View(markalar);
        }
        public ActionResult Peugeot()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 16).ToList();

            return View(markalar);
        }
        public ActionResult MercedesBenz()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 17).ToList();

            return View(markalar);
        }
        public ActionResult Audi()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 6).ToList();

            return View(markalar);
        }
        public ActionResult BMW()
        {
            var markalar = c.Uruns.Where(x => x.MarkaID == 4).ToList();

            return View(markalar);
        }
    }
}

WebApplication11/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>HAK4 ARAÇ KİRALAMA</title>
    <link href="~/web/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">HAK4 ARAÇ KİRALAMA</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-eye"></i>
        </button><!-- Navbar Search-->
   <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
       <div class="input-group" style="margin-right:40px;color:white">
           <div style="padding-top:15px">
               @Session["ad"]  @Session["soyad"]
           </div>
           <a href="@Session["resim"]" target="_blank"> <img width="50" height="50" /></a>
       </div>
   </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    @Html.ActionLink("Hesabım", "AddminCagir", "Admin", new { id = Session["id"] }, new { @class = "dropdown-item" })
                    <div class="dropdown-divider"></div>
                    @Html.ActionLink("Çıkış Yap", "LogOut", "Login", new { }, new { @class = "dropdown-item" })

                </div>
            </li>
        </ul>
    </nav> <div>
    @using (Html.BeginForm("Index", "Anasayfa", FormMethod.Post))
    {<button class="login100-form-btn" style="font-size:20px; background-color:white;float:right">
            Ana Sayfaya git
        </button>}
</div>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">MENÜ</div>
                        <a class="nav-link" href="/Marka/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-cubes"></i></div>
                            Markalar
                        </a>
                        <a class="nav-link" href="/Urun/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-archive"></i></div>
                            Ürünler
                        </a>
                       
                        <a class="nav-link" href="/Admin/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-handshake"></i></div>
                           Adminler
                        </a>
                        
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Tüm Hakları Saklıdır &copy; 2021 - HAKAN BÖBREK</div>

                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/web/dist/js/scripts.js"></script>
</body>
</html>





















































@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <script src="~/Scripts/modernizr-2.8.3.js"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />

        </div>

        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
    </body>
    </html>*@

WebApplication11/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>

    <title>@ViewBag.Title - HAK4 ARAÇ KİRALAMA</title>
    <link href="~/Content/baslangic.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

</head>
<body>

    <div class="kategori">
        <br />  @using (Html.BeginForm("Giris", "Login", FormMethod.Post))
        {<button class="login100-form-btn" style="font-size:20px; background-color:white;float:right">
                Giriş Yap
            </button> }
            <h2 style="text-align:center; color:white"> HAK4  ARAÇ  KİRALAMA</h2>
            <ul>
                <li><a href="\Anasayfa\Index">Ana sayfa</a></li>

                <li><a href="\Anasayfa\Hakkimizda">Hakkımızda</a></li>

                <li>
                    <a href="\Anasayfa\Araclar">Araçlarımız</a>
                </li>

              

                <li><a href="\Anasayfa\Iletisim">İletişim</a></li>
            </ul>
        </div>


    <div id="layoutSidenav_content">
        <main>
            @RenderBody()
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">

                    <div class="text-muted" style="position: fixed;  bottom: 0px;left: 0px;width: 100%;padding:15px;">  Tüm Hakları Saklıdır &copy; 2021 - HAKAN BÖBREK</div>

                </div>
            </div>
        </footer>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/web/dist/js/scripts.js"></script>

</body>
</html>

WebApplication11/Views/Shared/_LayoutPage2.cshtml
<!DOCTYPE html>
<html>
<head>

    <title>@ViewBag.Title - HAK4 ARAÇ KİRALAMA</title>
    <link href="~/Content/baslangic.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

</head>
<body>

    <div class="kategori">
        <br />  @using (Html.BeginForm("Giris", "Login", FormMethod.Post))
        {<button class="login100-form-btn" style="font-size:20px; background-color:white;float:right">
                Giriş Yap
            </button>}
        <h2 style="text-align:center; color:white"> HAK4  ARAÇ  KİRALAMA</h2>
        <ul>
            <li><a href="\Anasayfa\Index">Ana sayfa</a></li>

            <li><a href="\Anasayfa\Hakkimizda">Hakkımızda</a></li>

            <li>
                <a href="\Anasayfa\Araclar">Araçlarımız</a>
            </li>

         

            <li><a href="\Anasayfa\Iletisim">İletişim</a></li>
        </ul>
    </div>
    <table class="table table-bordered" style="margin-top:0px; margin-left:0px;width:20%;float:left">
        <tr style="background-color:maroon; color:white;">

            <th width="20%">MARKA ADI</th>

        </tr>
        <tr style="border:solid;font-size:25px;text-align:center;">
            <td><a style="color: black; text-decoration: none" href="\Anasayfa\BMW">BMW</a></td>
        </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Aston">Aston Martin</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Audi">Audi</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Citroen">Citroen</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Fiat">Fiat</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Renault">Renault</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Wolsvagen">WolksVagen</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Toyota">Toyota</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Opel">Opel</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\Peugeot">Peugeot</a></td> </tr>
        <tr style="text-align:center;border:solid;font-size:25px;"><td><a style="color: black; text-decoration: none" href="\Anasayfa\MercedesBenz">Mercedes-Benz</a></td> </tr>


    </table>

    <div id="layoutSidenav_content">
        <main>
            @RenderBody()
        </main>
        <footer class="py-4 bg-light mt-auto" > 
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                   
                    <div class="text-muted" style="position: fixed;  bottom: 0px;left: 0px;width: 100%;padding:15px;">  Tüm Hakları Saklıdır &copy; 2021 - HAKAN BÖBREK</div>

                </div>
            </div>
        </footer>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/web/dist/js/scripts.js"></script>

</body>
</html>